name: CodeQuality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CodeQuality
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install black
    - name: mypy
      run: |
        mypy faux_sure
    - name: black
      run: |
        black faux_sure